services:
  asir_bind9:
    container_name: asir_bind9
    image: internetsystemsconsortium/bind9:9.16
    networks:
      bind9_subnet:
        ipv4_address: 10.1.0.254
    volumes:
      - ./home/asir2a/Documentos/SRI/conf:/etc/bind
      - ./home/asir2a/Documentos/SRI/zonas:/var/lib/bind
  asir_cliente:
    container_name: asir_cliente
    image: alpine
    networks:
      - bind9_subnet
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    dns:
      - 10.1.0.254  # el contenedor dns server
networks:
  bind9_subnet: 
    external: true